# Generated by Django 6.1.1 on 2026-09-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0006_contactinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected',
        ),
    ]
