# Generated by Django 6.1.1 on 2026-09-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_remove_project_year_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='slug',
        ),
    ]
