# Generated by Django 6.1.1 on 2026-09-17 08:59

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_remove_projecttype_slug_remove_tool_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects', to='porfolio.projecttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects', to='porfolio.tool'),
        ),
    ]
