# Generated by Django 6.1.1 on 2026-09-17 09:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0004_alter_project_project_types_alter_project_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_types',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.CreateModel(
            name='ProjectProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_type_items', to='porfolio.project')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='porfolio.projecttype')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_items', to='porfolio.project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='porfolio.tool')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
