# Generated by Django 6.1.1 on 2026-09-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0005_remove_project_project_types_remove_project_tools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(choices=[('government', 'Government / LGU'), ('utilities', 'Utilities'), ('real_estate', 'Real Estate'), ('engineering', 'Engineering / Construction'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('research', 'Research / Academia'), ('other', 'Other')], max_length=50)),
                ('inquiry', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
