# Generated by Django 6.1.1 on 2026-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0007_alter_project_options_remove_project_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected',
            field=models.BooleanField(default=False, help_text='Include this project in the selected work section.'),
        ),
    ]
