# Generated by Django 6.1.1 on 2026-09-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0008_project_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name'], 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
